### ISSUE TITLE
Cannot run e2e tests since moving to OSX machine

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#310]
#### Expected behavior
- to be able to run e2e tests
#### Actual behavior
- running `gulp test` throws `Error: spawn webdriver-manager ENOENT`:
#### Steps to reproduce the behavior
1. be on my machine
2. pull latest of either master or 1.x branches
3. clean npm and bower install
4. run `gulp test` and see the following output:

```
[12:18:24] Using gulpfile ~/code/angular-esri-map/gulpfile.js
[12:18:24] Starting 'karma-coverage'...
[12:18:24] Starting 'build'...
[12:18:24] Starting 'lint'...
18 10 2016 12:18:24.864:INFO [karma]: Karma v0.13.22 server started at http://localhost:8080/
18 10 2016 12:18:24.869:INFO [launcher]: Starting browser Chrome
18 10 2016 12:18:26.530:INFO [Chrome 54.0.2840 (Mac OS X 10.11.4)]: Connected on socket GNKN4byebjsvzQrbAAAA with id 20121662
Chrome 54.0.2840 (Mac OS X 10.11.4): Executed 36 of 37 (skipped 1) SUCCESS (0.24 secs / 0.106 secs)
[12:18:27] Finished 'lint' after 2.69 s
[12:18:27] Starting 'clean'...
[12:18:27] Finished 'karma-coverage' after 3.22 s
[12:18:27] Finished 'clean' after 18 ms
[12:18:27] Starting 'build-core-js'...
[12:18:27] Finished 'build-core-js' after 222 ms
[12:18:27] Starting 'build-js'...
[12:18:27] Finished 'build-js' after 294 ms
[12:18:27] Starting 'ngdocs'...
[12:18:28] Finished 'ngdocs' after 353 ms
[12:18:28] Finished 'build' after 3.58 s
[12:18:28] Starting 'serve-test'...
[12:18:28] Finished 'serve-test' after 246 ms
[12:18:28] Starting 'test'...
[12:18:28] gulp-angular-protractor - The plugin is retrieved and will start soon
[12:18:28] gulp-angular-protractor - We will try to start and stop automatically the WebDriver server
[12:18:28] gulp-angular-protractor - The selenium address is: http://localhost:4444/wd/hub
[12:18:28] gulp-angular-protractor - The selenium address used is: http://localhost:4444/wd/hub
[12:18:28] gulp-angular-protractor - The selenium shutdown address used is: http://localhost:4444/selenium-server/driver/?cmd=shutDownSeleniumServer
[BS] Local URL: http://localhost:9002
[BS] External URL: http://192.168.0.8:9002
[BS] Serving files from: test
[12:18:28] gulp-angular-protractor - We have the config file to the following path: /Users/tom6947/code/angular-esri-map/test/e2e/conf.js
[12:18:28] gulp-angular-protractor - Webdriver standalone will be updated
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.19/chromedriver_mac32.zip...
chromedriver_2.19.zip downloaded to /Users/tom6947/code/angular-esri-map/node_modules/gulp-angular-protractor/node_modules/gulp-protractor/node_modules/protractor/selenium/chromedriver_2.19.zip
selenium-server-standalone-2.47.1.jar downloaded to /Users/tom6947/code/angular-esri-map/node_modules/gulp-angular-protractor/node_modules/gulp-protractor/node_modules/protractor/selenium/selenium-server-standalone-2.47.1.jar
[12:18:31] gulp-angular-protractor - Webdriver standalone is updated
[12:18:31] gulp-angular-protractor - Webdriver standalone server will be started
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn webdriver-manager ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by tomwayson** [comment]
#315 fixed the e2e tests for me. I'll make the same package.json updates to master and if they work on that branch, then we can close this issue.

**Comment by jwasilgeo** [comment]
@tomwayson any luck with this? I can take it over, just let me know. Thanks!

**Comment by tomwayson** [comment]
I've not had a chance yet. If you've got the time, go for it and I will test.

**Comment by jwasilgeo** [comment]
When you have a chance, please try with `master`.  https://github.com/Esri/angular-esri-map/commit/9da5a11cb842093ee2250c5d9466377c2a3b8246

**Comment by jwasilgeo** [comment]
@tomwayson we're good to close this now, is that right?

**Comment by tomwayson** [comment]
yup. thx!
