### ISSUE TITLE
viewOptions error after Angular 1.6.0 update

### ISSUE THREAD

**Issue by BjRnJ** [Esri/angular-esri-map#314]
After the Angular 1.6.0 update angular-esri-map (2.0.1) seems to be breaking over viewOptions. The following error is logged:

`TypeError: this.viewOptions is not a function
    at new EsriMapViewController (http://localhost:9000/bower_components/angular-esri-map/dist/angular-esri-map.js:337:33)
    at Object.invoke (http://localhost:9000/bower_components/angular/angular.js:4839:19)
    at $controllerInit (http://localhost:9000/bower_components/angular/angular.js:10692:34)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:9569:35)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8878:13)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:9632:11)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8878:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8881:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8881:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8881:13) <div ng-view="" class="ng-scope" data-ng-animate="1">`

Changing line 337 of angular-esri-map.js from `self.options = this.viewOptions() || {};` to `self.options = {};` solves the problem but of course the default viewOptions are not initialised. 

Does anyone know how to properly fix this issue?

**Comment by jwasilgeo** [comment]
@BjRnJ thank you for pointing this out and submitting the issue.  I just noticed this too, recently.  I'll make it a priority to investigate and see what has changed b/w Angular 1.5.x and 1.6.0.  Perhaps something here will help illuminate this, and I'll look into it soon. https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-services-$compile

**Comment by BjRnJ** [comment]
Thanks for the quick response and making it a priority :)

**Comment by jwasilgeo** [comment]
@BjRnJ we'll have some updates to fix this soon.  Angular 1.6.0 introduced some breaking changes.

**Comment by BjRnJ** [comment]
Nice! Thanks for the update

**Comment by bcanseco** [comment]
Getting this error with angular 1.5.8 as well.

**Comment by jwasilgeo** [comment]
Fixed for v1 and master branches in PR #320 and PR #321.  The next releases of both of those branches will include the fix.

**Comment by jwasilgeo** [comment]
There are new releases out now that should solve your previous issues with the AngularJS 1.6 breaking change.

https://github.com/Esri/angular-esri-map/releases/tag/v1.1.8

https://github.com/Esri/angular-esri-map/releases/tag/v2.0.2
